### PR TITLE
Fix features

### PR DESCRIPTION
**Pull request by chlewe**
Remove dependency of (implicit) feature `elements` upon `bitcoin` by using `elements::bitcoin`. Fix GitHub CI to test for successful compilation using each of these features separately.

Proposed in #21.

### CODE REVIEW

**Comment by sanket1729** [comment]
I think there are two different ways of looking at features here:

>  there is no way how dependency / implicit feature elements can enable dependency / implicit dependency bitcoin.


1) Features as dependency tree: I think when you say there is no way to have elements without bitcoin, you mean making sure that the rust-bitcoin crate is not being used as a dependency. 

2) Features are simplicity extensions: In this way of separation, when we are using simplicity with elements extension, we can use both rust-elements and rust-bitcoin. But the jets are available only for elements intropsection. 

I think we should classify our features by the latter method. If possible in rust, we should also mark features as incompatible with each other. That is, you can run in both elements and the bitcoin feature.

**Comment by apoelstra** [comment]
@sanket1729 unfortunately we can't make features incompatibile with each other, so we have made sure that it is possible to have both features enabled.

The problem that this PR addresses is that right now you can't have `elements` *without* `bitcoin`

**Comment by apoelstra** [comment]
@chlewe I would like it to be possible to use `elements` without `bitcoin`. This is what we want for use with elements-miniscript, for example.

Making the dependency explicit fixes the compilation issue but I'd like to remove the dependency. Heads up that you can access the rust-bitcoin crate through rust-elements, as `elements::bitcoin`.

**Comment by chlewe** [comment]
As far as I can see, the namespaces of features and dependencies get properly separated in [Rust 1.60](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features). In earlier versions, implicit features cannot enable other features / dependencies because implicit features are defined in `[dependencies]` and not in `[features]`. [Incompatible features should be avoided](https://doc.rust-lang.org/cargo/reference/features.html#mutually-exclusive-features).

**Comment by apoelstra** [comment]
@chlewe the two features are not incompatible, are they?

This fix looks great, exactly what I was looking for. If there are actual incompatibilties we should find and fix those but they can wait..

**Review by apoelstra — APPROVED** [review]
ACK 0385213c394e39423b8b6e273901f67602820f88

**Comment by chlewe** [comment]
Right now, all features are compatible and no feature depends on another.

**Pull request merged**
