### PR TITLE
Elements Miniscript rev 2022-03

### PR DESCRIPTION
**Pull request by chlewe**
Update to latest combination of `rust-bitcoin`, `rust-elements` and `rust-miniscript`.

# Todo
- [x] Update `Cargo.toml` after official release of `rust-bitcoin` v0.28.0, `rust-miniscript` v7.0.0 and `rust-elements` v0.19.0 (?)

### CODE REVIEW

**Comment by apoelstra** [comment]
This does not compile with rustc 1.41.0 and `--features=elements`.

Looking at CI, it appears that we misspell `FEATURES` as `FEATUERS` so we do not test this :)

Can you fix both things?

**Comment by apoelstra** [comment]
Actually, even on master
```
cargo +1.41.0 test --no-default-features --features=elements
```
fails to compile. (It does compile with just `--features=elements`, which I guess turns `bitcoin` on.) @chlewe can you open another PR which fixes that issue, and which fixes the typo in the CI configuration?

**Comment by chlewe** [comment]
@apoelstra I opened PR #23. Please check if it does what you proposed. I will rebase this PR afterwards.

**Review by apoelstra — APPROVED** [review]
ACK 90b45913c1b7698170ef97c47a764e53073ddf42

**Pull request merged**
